FROM gcr.io/oss-fuzz-base/base-builder@sha256:1051d1a0a51f82987e4fa36f85dd8cee525df635f8523ac35575086979625e67

ENV DEBIAN_FRONTEND=noninteractive
ENV SWIFT_VERSION=5.7.3
ENV SWIFT_PLATFORM=ubuntu22.04
ENV SWIFT_BRANCH=swift-${SWIFT_VERSION}-release
ENV SWIFT_WEBROOT=https://download.swift.org

# Update and install system dependencies
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list \
    && sed -i 's|http://security.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get upgrade -y

# Install necessary packages for Swift and building
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        software-properties-common \
        wget \
        curl \
        git \
        libatomic1 \
        libxml2 \
        netcat-openbsd \
        lsof \
        perl \
        clang \
        libc6-dev \
        libcurl4 \
        libedit2 \
        libgcc-11-dev \
        libpython3.10 \
        libsqlite3-0 \
        libstdc++-11-dev \
        libxml2-dev \
        libz3-dev \
        pkg-config \
        tzdata \
        unzip \
        zlib1g-dev

# Install Swift toolchain
RUN SWIFT_ARCHIVE_NAME=swift-$SWIFT_VERSION-$SWIFT_PLATFORM \
    && SWIFT_URL=$SWIFT_WEBROOT/$SWIFT_BRANCH/$(echo $SWIFT_PLATFORM | tr -d .)/swift-$SWIFT_VERSION/$SWIFT_ARCHIVE_NAME.tar.gz \
    && wget $SWIFT_URL \
    && wget $SWIFT_URL.sig \
    && gpg --keyserver keyserver.ubuntu.com --recv-keys \
        "A62AE125BBBFBB96A6E042EC925CC1CCED3D1561" \
    && gpg --batch --verify $SWIFT_ARCHIVE_NAME.tar.gz.sig $SWIFT_ARCHIVE_NAME.tar.gz \
    && tar -xvzf $SWIFT_ARCHIVE_NAME.tar.gz --directory / --strip-components=1 \
    && rm -rf $SWIFT_ARCHIVE_NAME.tar.gz $SWIFT_ARCHIVE_NAME.tar.gz.sig

# Set up Swift environment
ENV PATH="/usr/bin:${PATH}"
ENV SWIFTC="/usr/bin/swiftc"
ENV SWIFT="/usr/bin/swift"

# Clone the repository
RUN git clone --depth 1 https://github.com/apple/swift-nio.git

# Copy the build script
COPY build.sh $SRC/

# Set working directory
WORKDIR $SRC/swift-nio