FROM gcr.io/oss-fuzz-base/base-builder@sha256:c099d3d710d12d5d9a39498463ff10973977d1c7a85e9a0fbe00c7f0a0fa9fb8

RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    libtool \
    pkg-config \
    cmake \
    make \
    g++ \
    git \
    wget \
    tar \
    gzip \
    bzip2 \
    xz-utils \
    libsonic-dev \
    libpcaudio-dev \
    libpulse-dev \
    libasound2-dev \
    libsndfile1-dev \
    libmp3lame-dev \
    libmpg123-dev \
    libgsm1-dev \
    libportaudio2 \
    portaudio19-dev \
    libsamplerate0-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libicu-dev \
    libunwind-dev \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install newer CMake to meet version requirements (3.8-3.10)
RUN wget https://github.com/Kitware/CMake/releases/download/v3.10.3/cmake-3.10.3-Linux-x86_64.tar.gz \
    && tar -xzf cmake-3.10.3-Linux-x86_64.tar.gz \
    && cp -r cmake-3.10.3-Linux-x86_64/* /usr/local/ \
    && rm -rf cmake-3.10.3-Linux-x86_64 cmake-3.10.3-Linux-x86_64.tar.gz

# Clone espeak-ng repository
RUN git clone https://github.com/espeak-ng/espeak-ng.git

WORKDIR espeak-ng

COPY build.sh $SRC/